version: '3.0'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/src/myapp
    depends_on:
      - db
    links:
      - "db:db"
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ../db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
